### ISSUE TITLE
Spring Cloud Consumer argument payload is always getting byte array object.

### ISSUE THREAD

**Issue by suresh-chidham** [spring-cloud-stream-app-starters/transform#6]
I have created testprocessor app using spring cloud stream 2.0.
Created the sample stream
stream create TEST1 --definition "http --server.port=8888  | testprocessor  | uploader --spring.cloud.stream.bindings.input.contentType='text/plain1' " 

Deployed in Spring cloud local server.

testprocessor app's method signature is 
@StreamListener(Processor.INPUT)
	@SendTo(Processor.OUTPUT)
	public String transform(Object payload)

In application.properties of this app, i have configured below
spring.cloud.stream.bindings.input.content-type=application/json
spring.cloud.stream.bindings.output.content-type=application/json

Sample input data:
http post --contentType 'application/json' --data '{"isbn": "1599869772", "title": "The Art of War", "author": "Sun Tzu"}' --target http://localhost:8888

When i post above sample data, i am always getting Object payload is byte[] object like [B@5b2ff6e7 but not getting actual JSON String. 
Please can you help on this issue?

Note: If i build same testprocessor app using spring cloud stream 1.3.1 version. It is working fine. I am getting JSON string.  Why it is not working using spring cloud stream 2.0.1

**Comment by artembilan** [comment]
Related StackOverflow question: https://stackoverflow.com/questions/53083818/spring-cloud-consumer-argument-payload-is-always-getting-byte-array-object

Please, don't duplicate the same problem in different places.

I'm not going to close this issue, because it is really a problem and we need to fix it somehow.

**Comment by sabbyanandan** [comment]
We have addressed this problem in SCSt Elmhurst.SR2 and as well in all the associated Apps including the `transform` processor. 

@suresh-chidham: please retry it on [Darwin.SR3](https://docs.spring.io/spring-cloud-stream-app-starters/docs/Darwin.SR3/reference/htmlsingle/) apps - we have new bit.ly links, too. If you're building a custom app, you'd have to be on Elmhurst.SR2 foundation and set the content-type to `text/plain` - see [here](https://github.com/spring-cloud-stream-app-starters/transform/commit/87fe62ff6d2d7f6f3ba2d506e1ed9d3994739f52).

Feel free to open a new issue if you see any other anomaly.
